# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dlg_logo(object):
    def setupUi(self, Dlg_logo):
        Dlg_logo.setObjectName("Dlg_logo")
        Dlg_logo.resize(480, 270)
        self.label = QtWidgets.QLabel(Dlg_logo)
        self.label.setGeometry(QtCore.QRect(0, 0, 480, 270))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/docs/background.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")

        self.retranslateUi(Dlg_logo)
        QtCore.QMetaObject.connectSlotsByName(Dlg_logo)

    def retranslateUi(self, Dlg_logo):
        _translate = QtCore.QCoreApplication.translate
        Dlg_logo.setWindowTitle(_translate("Dlg_logo", "Dialog"))
import ui_rc
